apiVersion: v2
name: insecure-app
description: Intentionally insecure Helm chart for testing purposes
type: application
version: 0.3.1
appVersion: "1.0.0"
maintainers:
- email: james@latio.tech
  name: Latio Tech