apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-server
  namespace: erlang
  labels:
    app: ssh-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssh-server
  template:
    metadata:
      labels:
        app: ssh-server
    spec:
      containers:
      - name: ssh-server
        image: confusedcrib/erlang-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2222
          name: ssh
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-server
  namespace: erlang
spec:
  type: ClusterIP
  ports:
  - port: 2222
    targetPort: 2222
    protocol: TCP
    name: ssh
  selector:
    app: ssh-server 