apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: {{ .Values.busybox.namespace }}
  labels:
    app: busybox
spec:
  replicas: {{ .Values.busybox.replicas }}
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: {{ .Values.busybox.image }}
        command: {{ toYaml .Values.busybox.command | nindent 8 }}
