apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.insecureJs.namespace | default "insecure-js" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.insecureJs.service.name | default "insecure-js" }}
  namespace: {{ .Values.insecureJs.namespace | default "insecure-js" }}
spec:
  selector:
    app: {{ .Values.insecureJs.appName | default "insecure-js" }}
  ports:
    - protocol: TCP
      port: {{ .Values.insecureJs.service.port | default 3000 }}
      targetPort: {{ .Values.insecureJs.service.targetPort | default 3000 }}
  type: NodePort


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.insecureJs.appName | default "insecure-js" }}
  namespace: {{ .Values.insecureJs.namespace | default "insecure-js" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.insecureJs.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.insecureJs.appName | default "insecure-js" }}
  template:
    metadata:
      labels:
        app: {{ .Values.insecureJs.appName | default "insecure-js" }}
    spec:
      containers:
        - name: {{ .Values.insecureJs.containerName | default "insecure-js" }}
          image: "{{ .Values.insecureJs.image.repository }}:{{ .Values.insecureJs.image.tag | default "latest" }}"
          env:
            - name: NODE_OPTIONS
              value: "--perf-basic-prof --interpreted-frames-native-stack"
          ports:
            - containerPort: {{ .Values.insecureJs.containerPort | default 3000 }}

---

apiVersion: v1
kind: Service
metadata:
  name: insecure-app-js
  namespace: {{ .Values.insecureJs.namespace | default "insecure-js" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ .Values.insecureJs.appName | default "insecure-js" }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: insecure-app-js-ingress
  namespace: {{ .Values.insecureJs.namespace | default "insecure-js" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /js
            pathType: Prefix
            backend:
              service:
                name: insecure-app-js
                port:
                  number: 3000

