apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.insecureAi.namespace | default "insecure-ai" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: insecure-ai-secrets
  namespace: {{ .Values.insecureAi.namespace | default "insecure-ai" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  openai-api-key: {{ .Values.insecureAi.env.openaiApiKey | b64enc }}
  gemini-api-key: {{ .Values.insecureAi.env.geminiApiKey | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.insecureAi.service.name | default "insecure-ai" }}
  namespace: {{ .Values.insecureAi.namespace | default "insecure-ai" }}
spec:
  selector:
    app: {{ .Values.insecureAi.appName | default "insecure-ai" }}
  ports:
    - port: {{ .Values.insecureAi.service.port | default 80 }}
      targetPort: {{ .Values.insecureAi.service.targetPort | default 5000 }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.insecureAi.appName | default "insecure-ai" }}
  namespace: {{ .Values.insecureAi.namespace | default "insecure-ai" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.insecureAi.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.insecureAi.appName | default "insecure-ai" }}
  template:
    metadata:
      labels:
        app: {{ .Values.insecureAi.appName | default "insecure-ai" }}
    spec:
      containers:
      - name: {{ .Values.insecureAi.containerName | default "insecure-ai" }}
        image: {{ .Values.insecureAi.image.repository }}:{{ .Values.insecureAi.image.tag | default "latest" }}
        ports:
        - containerPort: {{ .Values.insecureAi.containerPort | default 5000 }}
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: insecure-ai-secrets
              key: openai-api-key
              optional: true
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: insecure-ai-secrets
              key: gemini-api-key
              optional: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: insecure-ai-ingress
  namespace: {{ .Values.insecureAi.namespace | default "insecure-ai" }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /ai/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.insecureAi.service.name | default "insecure-ai" }}
            port:
              number: {{ .Values.insecureAi.service.port | default 80 }} 